(source gnu)
(source melpa)

(depends-on "cask")
(depends-on "dash")
(depends-on "epl")
(depends-on "f")
(depends-on "package-build")
(depends-on "pallet")
(depends-on "s")
(depends-on "shut-up")

(depends-on "dayone")
(depends-on "redo+")
(depends-on "expand-region")
(depends-on "historyf")

(depends-on "git-gutter")
(depends-on "helm" :git "git@github.com/emacs-helm/helm.git")
(depends-on "helm-c-moccur")
(depends-on "auto-complete")
(depends-on "perl-completion")
(depends-on "popwin")
(depends-on "quickrun")
(depends-on "auto-async-byte-compile")
(depends-on "emmet-mode")
(depends-on "scss-mode")
(depends-on "slim-mode")
(depends-on "js2-mode")
(depends-on "coffee-mode")
(depends-on "color-theme")
(depends-on "color-theme-solarized")
(depends-on "dash-at-point")
(depends-on "helm-open-junk-file" :git "git@github.com:masaaki1001/helm-open-junk-file.git")
(depends-on "pbcopy" :git "git@github.com:jeffgran/pbcopy.el.git")
(depends-on "yasnippet")
(depends-on "helm-c-yasnippet")
(depends-on "anzu")
(depends-on "smartrep")
(depends-on "multiple-cursors")
(depends-on "open-junk-file")
(depends-on "nginx-mode")
(depends-on "howm")
(depends-on "historyf")
(depends-on "smartparens")
